name: "github action workflow"

on:
  push:
    branches:
      - master
      - testing

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: "running date command"
        run: date
        shell: bash

      - name: "getting-os-details"
        run: cat /etc/os-release
        shell: bash

      - name: "user details"
        run: whoami
        shell: bash

      - name: "current working directory details before checkout"
        run: |
          pwd
          ls -al

      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "current working directory details after checkout"
        run: |
          pwd
          ls -al

      - name: "installing terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: "terraform verison"
        run: terraform version 
   
            
      - name: "running script.sh"
        run: |
          chmod +x script.sh
          ./script.sh

